### ISSUE TITLE
Request for Pretrained Code

### ISSUE THREAD

**Issue by lmsdss** [muyangyi/SimSeg#3]
Hi there,
I hope you are doing well. I came across your project and found it very interesting. I noticed that you have provided pre-trained checkpoints for the model, but I couldn't find the code used for pretraining.
Having the pretraining code would be immensely helpful for understanding the model architecture, training procedure, and adapting it to my specific use case.
Thank you for your time and consideration. Looking forward to your response.

**Comment by muyangyi** [comment]
Hi, thank you for your interest of our project. 
The pre-training is conducted on 4 machines with 8 V100 GPUs each. The multinode logic is implemented specifically for our own cluster.
It is difficult for us to find 32 GPUs other than our cluster so as to verify the correctness of the pre-training code. So currently we don't have plans to release them.
Do you consider using other public CLIP repo? It would be convenient to replace their pooling layer by our proposed LoDA to reproduce the same result.

**Comment by zbb1111** [comment]
Thank you for your excellent article! How do I use public CLIP repo and then replace the pooling layer with LoDA? Looking forward to your reply and wishing you all the best!
