### ISSUE TITLE
About Innovation Points

### ISSUE THREAD

**Issue by zbb1111** [muyangyi/SimSeg#6]
Thank you very much for your excellent article. I would like to ask which lines of code are the innovative points of the model in segmentation. Looking forward to your reply!

**Comment by muyangyi** [comment]
The main contribution of this paper is LoDA (Locality-Driven Alignment) that enables a vanilla CLIP to produce interpretable text-to-image similarity maps.   
Then we implement the SimSeg framework to transform the similarity maps into segmentation maps.
